rules:
  unpinned-uses:
    disable: true
  cache-poisoning:
    ignore:
      # Enabling caching is OK for non-release workflows
      - ci-build.yml
      - ci-build-native-build.yml
      - ci-build-db-version-matrix.yml
      - project-keeper-verify.yml
      - test_on_windows.yml
      - test_linux_build_on_windows.yml