sources:
  - type: maven
    path: pom.xml
  - type: maven
    path: shared-model-classes/pom.xml
    modules:
      - maven_central
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
    advertise: false
    artifacts:
      # [itest->dsn~customize-release-artifacts-custom~0]
      - target/project-keeper-shared-model-classes-${version}.jar
  - type: maven
    path: project-keeper/pom.xml
    modules:
      - maven_central
      - integration_tests
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: project-keeper-cli/pom.xml
    modules:
      - maven_central
      - integration_tests
      - jar_artifact
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: project-keeper-maven-plugin/pom.xml
    modules:
      - maven_central
      - integration_tests
      - udf_coverage
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: maven-project-crawler/pom.xml
    modules:
      - maven_central
      - udf_coverage
      - integration_tests
    advertise: false
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: shared-test-setup/pom.xml
    advertise: false
    modules:
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
version:
  fromSource: project-keeper/pom.xml
excludes:
  # PK can't use itself as a Maven plugin
  - regex: "W-PK-CORE-151: Pom file .* contains no reference to project-keeper-maven-plugin."
  # Build with Java 21 fails due to missing JavaDoc comments, see https://github.com/exasol/project-keeper/issues/596
  - "E-PK-CORE-17: Missing required file: '.github/workflows/ci-build-next-java.yml'"
  # No configuration necessary for aggregator POM
  - "E-PK-CORE-103: Missing parent declaration in 'pom.xml'"
  - "E-PK-CORE-17: Missing required file: 'pk_generated_parent.pom'"
  - regex: "E-PK-CORE-17: Missing required file: 'src/test/resources/.*'"
  - regex: "E-PK-CORE-17: Missing required file: '.settings/.*'"
linkReplacements:
  - https://eclipse-ee4j.github.io/jsonb-api|https://projects.eclipse.org/projects/ee4j.jsonp
build:
  workflows:
    # [itest->dsn~customize-build-process.ci-build~0]
    # [itest->dsn~customize-build-process.insert-step-after~0]
    # [itest->dsn~customize-build-process.replace-step~0]
    - name: "ci-build.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          job: build-and-test
          stepId: setup-java
          content:
            name: Set up Go
            id: setup-go
            uses: actions/setup-go@v5
            with:
              go-version: "1.22"
              cache-dependency-path: .project-keeper.yml
        - action: INSERT_AFTER
          job: build-and-test
          stepId: setup-go
          content:
            name: Install Go tools
            id: install-go-tools
            run: go install github.com/google/go-licenses@v1.6.0
        - action: REPLACE
          job: build-and-test
          stepId: build-pk-verify
          content:
            name: Run tests and build with Maven
            id: maven-build
            run: |
              mvn -T 1C --batch-mode clean install verify \
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                  -DtrimStackTrace=false
            env:
              GITHUB_TOKEN: ${{ github.token }} # Required for integration tests
        - action: INSERT_AFTER
          job: build-and-test
          stepId: sonar-analysis
          content:
            name: Run project-keeper itself
            id: build-pk-verify
            run: mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify --projects .
        - action: INSERT_AFTER
          job: build-and-test
          stepId: build-pk-verify
          content:
            name: Verify that metrics.json was created
            id: verify-metrics-json
            run: |
              # Ensure that file exists:
              ls -lh coverage-aggregator/target/metrics.json
              cat coverage-aggregator/target/metrics.json

    # [itest->dsn~customize-build-process.dependency-check~0]
    - name: "dependencies_check.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          job: report_security_issues
          stepId: setup-jdks
          content:
            name: Install Project Keeper
            id: install-project-keeper
            # This fixes https://github.com/exasol/project-keeper/issues/330
            run: |
              mvn --batch-mode --threads 1C install \
                  -Dmaven.test.skip=true -Dproject-keeper.skip=true \
                  -Dossindex.skip=true -Dmaven.javadoc.skip=true \
                  -Derror-code-crawler.skip=true -Dreproducible.skip=true

    # [itest->dsn~customize-build-process.dependency-update~0]
    - name: "dependencies_update.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: check-branch
          content:
            name: Install Project Keeper
            id: install-project-keeper
            # This fixes https://github.com/exasol/project-keeper/issues/330
            run: |
              mvn --batch-mode --threads 1C install \
                  -Dmaven.test.skip=true -Dproject-keeper.skip=true \
                  -Dossindex.skip=true -Dmaven.javadoc.skip=true \
                  -Derror-code-crawler.skip=true -Dreproducible.skip=true

    # [itest->dsn~customize-build-process.release~0]
    - name: "release.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: check-ci-build-status
          content:
            name: Install Project Keeper
            id: install-project-keeper
            # Required for running PK verify-release
            run: |
              mvn --batch-mode --threads 1C install \
                  -Dmaven.test.skip=true -Dproject-keeper.skip=true \
                  -Dossindex.skip=true -Dmaven.javadoc.skip=true \
                  -Derror-code-crawler.skip=true -Dreproducible.skip=true
