sources:
  - type: maven
    path: pom.xml
  - type: maven
    path: shared-model-classes/pom.xml
    modules:
      - maven_central
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
    advertise: false
  - type: maven
    path: project-keeper/pom.xml
    modules:
      - maven_central
      - integration_tests
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: project-keeper-cli/pom.xml
    modules:
      - maven_central
      - integration_tests
      - jar_artifact
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: project-keeper-maven-plugin/pom.xml
    modules:
      - maven_central
      - integration_tests
      - udf_coverage
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: maven-project-crawler/pom.xml
    modules:
      - maven_central
      - udf_coverage
      - integration_tests
    advertise: false
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: shared-test-setup/pom.xml
    advertise: false
    modules:
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
version:
  fromSource: project-keeper/pom.xml
excludes:
  # PK can't use itself as a Maven plugin
  - regex: "W-PK-CORE-151: Pom file .* contains no reference to project-keeper-maven-plugin."
  # PK already uses Java 17 for building
  - "E-PK-CORE-17: Missing required file: '.github/workflows/ci-build-next-java.yml'"
  # Workflows must install PK itself before using it in the build
  - "E-PK-CORE-18: Outdated content: '.github/workflows/dependencies_check.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/dependencies_update.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release.yml'"
  # No configuration necessary for aggregator POM
  - "E-PK-CORE-103: Missing parent declaration in 'pom.xml'"
  - "E-PK-CORE-17: Missing required file: 'pk_generated_parent.pom'"
  - regex: "E-PK-CORE-17: Missing required file: 'src/test/resources/.*'"
  - regex: "E-PK-CORE-17: Missing required file: '.settings/.*'"
linkReplacements:
  - https://eclipse-ee4j.github.io/jsonb-api|https://projects.eclipse.org/projects/ee4j.jsonp
