sources:
  - type: maven
    path: pom.xml
  - type: maven
    path: shared-model-classes/pom.xml
    modules:
      - maven_central
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
    advertise: false
    artifacts:
      # [itest->dsn~customize-release-artifacts-custom~0]
      - target/project-keeper-shared-model-classes-${version}.jar
  - type: maven
    path: project-keeper/pom.xml
    modules:
      - maven_central
      - integration_tests
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: project-keeper-cli/pom.xml
    modules:
      - maven_central
      - integration_tests
      - jar_artifact
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: project-keeper-maven-plugin/pom.xml
    modules:
      - maven_central
      - integration_tests
      - udf_coverage
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: maven-project-crawler/pom.xml
    modules:
      - maven_central
      - udf_coverage
      - integration_tests
    advertise: false
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: shared-test-setup/pom.xml
    advertise: false
    modules:
    parentPom:
      groupId: "com.exasol"
      artifactId: "project-keeper-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
version:
  fromSource: project-keeper/pom.xml
excludes:
  # PK can't use itself as a Maven plugin
  - regex: "W-PK-CORE-151: Pom file .* contains no reference to project-keeper-maven-plugin."
  # PK already uses Java 17 for building
  - "E-PK-CORE-17: Missing required file: '.github/workflows/ci-build-next-java.yml'"
  # Workflows must install PK itself before using it in the build
  - "E-PK-CORE-18: Outdated content: '.github/workflows/dependencies_check.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/dependencies_update.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release.yml'"
  # No configuration necessary for aggregator POM
  - "E-PK-CORE-103: Missing parent declaration in 'pom.xml'"
  - "E-PK-CORE-17: Missing required file: 'pk_generated_parent.pom'"
  - regex: "E-PK-CORE-17: Missing required file: 'src/test/resources/.*'"
  - regex: "E-PK-CORE-17: Missing required file: '.settings/.*'"
linkReplacements:
  - https://eclipse-ee4j.github.io/jsonb-api|https://projects.eclipse.org/projects/ee4j.jsonp
build:
  setupSteps:
    - name: Set up Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        cache-dependency-path: .project-keeper.yml
    - name: Install Go tools
      id: install-go-tools
      run: go install github.com/google/go-licenses@v1.6.0
  buildStep:
    name: Run tests and build with Maven
    id: maven-build
    run: mvn -T 1C --batch-mode clean verify
    env:
      GITHUB_TOKEN: ${{ github.token }} # Required for integration tests
  cleanupSteps:
    - name: Install project-keeper for self-verification
      run: mvn -T 1C --batch-mode install -DskipTests
    - name: Run project-keeper itself
      id: build-pk-verify
      run: mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify --projects .
