language: java
sudo: required
matrix:
  include:
    - jdk: openjdk11
git:
  depth: false
addons:
  sonarcloud:
    organization: exasol
    token:
      secure: c7okYs+ld2Warzroez4T8XBP0AgU768eegJUtIPzRd5Gnp6eU0/FVJ4PsRtF1C51sYq6Gd8h/ppoagqAj4P3fRpFsZaxEnUORzCzoqyhZ1LvnFgvHUStD/8RT70e4+8UasiyNYqQlAVlSC0j7PQwxbw/0Ik4kSp+hPcNOizz3pNSmQWZo24VYPhHRoVQZ6aqAb/xUWXkqPA7VPXWeauu5EgRdGAvkJwJYyRz3hoiLmZh2vGElhywmgb+FAuFWvLpGEqppkFUtBI311Beg1RBm+PvSbssja+TdFtm4CFt4l/50XP21MEm9vm/PUMpx0QOaFyBQ12vYniQdo4XQO+pKNkWGFdW+b20eQK+HEHK0cy6246ECkwg499BhzopHJEGs9d0/2599oABz+oQ4PWcbXXuc53oaZ/VZutzK8/9g3NXRYtlWIiswSeY7bIR1z6txEB+YXsj2IMwBz39QKmYQsxoE7wCniDexa6MaC+K7alULGnp484pZbj2OH+YR0KgqHC8gHsrWYEvxMq4C8o4kb8ssLjG+NLsv2rOE6iLGuCVIY19n3QOLAd8GrxYoEB5oh7tKzfhoiKI1eagwAQ4BBmhpM6L3PJERGWIdZ/nXEQx6gRm66wubtC2AQ655cH+1ASkLPHqbZaZSK1+lxCQvz1HfNySEGAnfj9pSNFqisA=
install:
  - git fetch --tags
script:
  - mvn clean install sonar:sonar project-keeper:verify
cache:
  directories:
    - "$HOME/.m2"
