package com.exasol.projectkeeper.validators.pom;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import org.w3c.dom.Document;

import com.exasol.projectkeeper.Validator;
import com.exasol.projectkeeper.sources.AnalyzedMavenSource;
import com.exasol.projectkeeper.sources.AnalyzedSource;
import com.exasol.projectkeeper.validators.finding.ValidationFinding;
import com.exasol.projectkeeper.validators.finding.ValidationFindingGroup;
import com.exasol.projectkeeper.validators.pom.io.PomFileReader;
import com.exasol.projectkeeper.validators.pom.io.PomFileWriter;

/**
 * This custimizes the parent POM file generated by {@link PomFileGenerator} in phase 3. This is required because it
 * needs the project dependencies as input.
 */
public class GeneratedPomFileCustomizer implements Validator {

    private final List<AnalyzedSource> analyzedSources;
    private final Path projectDir;

    public GeneratedPomFileCustomizer(final List<AnalyzedSource> analyzedSources, final Path projectDir) {
        this.analyzedSources = analyzedSources;
        this.projectDir = projectDir;
    }

    @Override
    public List<ValidationFinding> validate() {
        return analyzedSources.stream()
                .filter(AnalyzedMavenSource.class::isInstance)
                .map(AnalyzedMavenSource.class::cast)
                .map(this::customizeGeneratedPomFile)
                .flatMap(List::stream)
                .toList();
    }

    private List<ValidationFinding> customizeGeneratedPomFile(final AnalyzedMavenSource mavenSource) {
        final Path generatedPomPath = this.projectDir
                .resolve(mavenSource.getPath().getParent())
                .resolve(PomFileValidator.GENERATED_PARENT_POM_NAME);
        final Document pom = PomFileReader.parse(generatedPomPath);
        final List<ValidationFinding> findings = new ArrayList<>();
        findings.addAll(new MockitoAgentCustomizer(mavenSource).customize(pom));
        return wrapFindingsWithGroupThatWritesPom(pom, generatedPomPath, findings);
    }

    private List<ValidationFinding> wrapFindingsWithGroupThatWritesPom(final Document pom, final Path generatedPomPath,
            final List<ValidationFinding> findings) {
        if (findings.isEmpty()) {
            return findings;
        }
        return List.of(new ValidationFindingGroup(findings, () -> PomFileWriter.writeFile(pom, generatedPomPath)));
    }
}
