name: Project Keeper Verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Project Keeper
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-pk-${{ hashFiles('.github/workflows/project-keeper.sh') }}
          restore-keys: |
            ${{ runner.os }}-pk-

      - name: Project Keeper Verify
        run: bash .github/workflows/project-keeper.sh
