package com.exasol.projectkeeper.sources.analyze.golang;

import java.util.List;

import lombok.Builder;

/**
 * This data class represents information about a Go module that was generated by executing the {@code go list} command
 * for getting the direct dependencies.
 */
@Builder
class ModuleInfo {
    private final String moduleName;
    private final List<Dependency> dependencies;

    @Builder
    static class Dependency {
        private final String moduleName;
        private final String version;

        /**
         * @return name of this module
         */
        public String getModuleName() {
            return this.moduleName;
        }

        /**
         * @return version of this dependency
         */
        public String getVersion() {
            return this.version;
        }
    }

    /**
     * @return name of the module
     */
    public String getModuleName() {
        return this.moduleName;
    }

    /**
     * @return list of dependencies of this module
     */
    public List<Dependency> getDependencies() {
        return this.dependencies;
    }
}
