package com.exasol.projectkeeper.sources.analyze.golang;

import java.util.List;

import lombok.Builder;
import lombok.Getter;

/**
 * This data class represents information about a Go module that was generated by executing the {@code go list} command
 * for getting the direct dependencies.
 */
@Getter
@Builder
class ModuleInfo {
    private final String moduleName;
    private final List<Dependency> dependencies;

    @Getter
    @Builder
    static class Dependency {
        private final String moduleName;
        private final String version;
    }
}
