@startuml release_process

start
note right
  Triggered manually or
  on pushes to main branch.
end note
group **release.yml** workflow
  note right
    Generated
    by PK
  end note
  :Run PK **verify-release** as Maven plugin;
  group PK **verify-release**
    note right
      Implemented
      in PK
    end note
    if(Release date up-to-date?\n(allow skipping the release)) then (up-to-date)
      :Run PK **verify**;
      :Run additional release checks;
      :Write changelog content to file;
      note right
        Required for creating
        the GitHub release
      end note
    else (invalid/outdated)
      :Fail build;
      stop
    endif
  end group
  :Run **mvn verify**;
  if(Maven Central deployment required) then (required)
    :Run **mvn deploy**;
  endif
  :Calculate checksums for release artifacts;
  :Create GitHub release;
  note right
    Reads changelog
    content from file
  end note
  :Attach release artifacts and
  checksums to GitHub release;
  note right
    Customizable
  end note
  :Send Slack notification
  for success & failure;
end group
stop
@enduml
