name: Report Security Issues for Repository
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  report_security_issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    outputs:
      created-issues: ${{ steps.security-issues.outputs.created-issues }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"

      - name: Install Projects
        # This fixes https://github.com/exasol/project-keeper/issues/330
        run: |
          mvn --batch-mode -T 1C install -DskipTests \
              -Dproject-keeper.skip=true -Dossindex.skip=true -Dmaven.javadoc.skip=true \
              -Djacoco.skip=true -Derror-code-crawler.skip=true -Dreproducible.skip=true

      - name: Generate ossindex report
        run: |
          mvn --batch-mode org.sonatype.ossindex.maven:ossindex-maven-plugin:audit \
              org.sonatype.ossindex.maven:ossindex-maven-plugin:audit-aggregate \
              -Dossindex.reportFile=$(pwd)/ossindex-report.json \
              -Dossindex.fail=false

      - name: Report Security Issues
        id: security-issues
        uses: exasol/python-toolbox/.github/actions/security-issues@main
        with:
          format: "maven"
          command: "cat ossindex-report.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output security issues (Debugging)
        run: |
          echo "$CREATED_ISSUES" > test.jsonl
          cat test.jsonl
        env:
          CREATED_ISSUES: ${{ steps.security-issues.outputs.created-issues }}

  start_dependency_udpate:
    needs: report_security_issues
    if: ${{ needs.report_security_issues.outputs.created-issues }}
    concurrency:
      cancel-in-progress: true
      group: "dependency_update"
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/dependencies_update.yml
    with:
      vulnerability_issues: ${{ needs.report_security_issues.outputs.created-issues }}
