name: Test on windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}
            ${{ runner.os }}-go-
      - name: Install Go tools
        run: go install github.com/google/go-licenses@latest
      - name: Build and install
        run: mvn --batch-mode clean install
      - name: Run project-keeper itself
        run: mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify -pl .